export const CUISINES = [
    { value: '', text: 'None' },
    { value: 'african', text: 'African' },
    { value: 'asian', text: 'Asian' },
    { value: 'american', text: 'American' },
    { value: 'british', text: 'British' },
    { value: 'cajun', text: 'Cajun' },
    { value: 'caribbean', text: 'Caribbean' },
    { value: 'chinese', text: 'Chinese' },
    { value: 'eastern european', text: 'Eastern European' },
    { value: 'european', text: 'European' },
    { value: 'french', text: 'French' },
    { value: 'german', text: 'German' },
    { value: 'greek', text: 'Greek' },
    { value: 'indian', text: 'Indian' },
    { value: 'irish', text: 'Irish' },
    { value: 'italian', text: 'Italian' },
    { value: 'japanese', text: 'Japanese' },
    { value: 'jewish', text: 'Jewish' },
    { value: 'korean', text: 'Korean' },
    { value: 'latin american', text: 'Latin American' },
    { value: 'mediterranean', text: 'Mediterranean' },
    { value: 'mexican', text: 'Mexican' },
    { value: 'middle eastern', text: 'Middle Eastern' },
    { value: 'nordic', text: 'Nordic' },
    { value: 'southern', text: 'Southern' },
    { value: 'spanish', text: 'Spanish' },
    { value: 'thai', text: 'Thai' },
    { value: 'vietnamese', text: 'Vietnamese' },
];
